version: '3.8'

services:
  app:
    build: .
    container_name: recept
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8083:8000"
    volumes:
      - .:/app
    restart: always